name = "SingleCell10xWriter"
uuid = "cc7c8505-e4bc-436c-ad73-9486aa03ac5c"
authors = ["Rasmus Henningsson <rasmus.henningsson@med.lu.se>"]
version = "0.1.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SingleCell10x = "eddce310-d14b-4c2d-aa06-cfe9e2f7af98"
SingleCellProjections = "03d38035-ed2f-4a36-82eb-797f1727ab2e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
HDF5 = "0.16, 0.17"
LinearAlgebra = "1"
SingleCell10x = "0.2"
SingleCellProjections = "0.3"
SparseArrays = "1"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
